#if ANDROID && BUNDLED_RESOURCE_TEST
using System;
using System.Collections.Generic;

namespace Library.Network
{
    // Canonical runtime table from the working 1403 APK, application assembly
    // SHA256: 0668a86de0adec777ec9c273de680822dfb4d12c4d8119628de7e1255cf42838.
    // Packet's legacy comparer treats same-named client/server types as equal.
    // List.Sort is unstable, so new metadata order can swap their wire IDs.
    internal static class OriginalAndroidPacketOrder
    {
        internal const string WireOrderNames = @"Library.Network.GeneralPackets.CheckVersion
Library.Network.GeneralPackets.Connected
Library.Network.GeneralPackets.Disconnect
Library.Network.GeneralPackets.GoodVersion
Library.Network.GeneralPackets.Ping
Library.Network.GeneralPackets.PingResponse
Library.Network.GeneralPackets.Version
Library.Network.ClientPackets.AccessoryCombineRequest
Library.Network.ServerPackets.AccessoryCombineResult
Library.Network.ServerPackets.AchievementProgressChanged
Library.Network.ServerPackets.AchievementTitleChanged
Library.Network.ClientPackets.Activation
Library.Network.ServerPackets.Activation
Library.Network.ClientPackets.AddHole
Library.Network.ServerPackets.AmmAmmunition
Library.Network.ClientPackets.Ammunition
Library.Network.ClientPackets.ApplyJoinGuildPacket
Library.Network.ClientPackets.ArmourDye
Library.Network.ClientPackets.AttachGem
Library.Network.ClientPackets.Attack
Library.Network.ClientPackets.AutinsBuy
Library.Network.ClientPackets.AutionsAdd
Library.Network.ClientPackets.AutionsFlash
Library.Network.ClientPackets.AutionsFlashIndex
Library.Network.ClientPackets.AutoFightConfChanged
Library.Network.ClientPackets.AutoPotionLinkChanged
Library.Network.ServerPackets.AutoTimeChanged
Library.Network.ClientPackets.BeltLinkChanged
Library.Network.ServerPackets.BlockAdd
Library.Network.ClientPackets.BlockAdd
Library.Network.ClientPackets.BlockRemove
Library.Network.ServerPackets.BlockRemove
Library.Network.ServerPackets.BuffAdd
Library.Network.ServerPackets.BuffChanged
Library.Network.ServerPackets.BuffPaused
Library.Network.ServerPackets.BuffRemove
Library.Network.ServerPackets.BuffTime
Library.Network.ClientPackets.CanelSellCharacter
Library.Network.ServerPackets.ChangeAttackMode
Library.Network.ClientPackets.ChangeAttackMode
Library.Network.ServerPackets.ChangePassword
Library.Network.ClientPackets.ChangePassword
Library.Network.ClientPackets.ChangePetMode
Library.Network.ServerPackets.ChangePetMode
Library.Network.ServerPackets.ChangeWeather
Library.Network.ClientPackets.Chat
Library.Network.ServerPackets.Chat
Library.Network.ServerPackets.ChatItem
Library.Network.ClientPackets.ClaimRedpacket
Library.Network.ServerPackets.ClientNameChanged
Library.Network.ServerPackets.CoinTossOnTarget
Library.Network.ClientPackets.ComSortingConf1Changed
Library.Network.ClientPackets.ComSortingConfChanged
Library.Network.ServerPackets.CombatTime
Library.Network.ClientPackets.CompanionAdopt
Library.Network.ServerPackets.CompanionAdopt
Library.Network.ClientPackets.CompanionAutoFeedUnlock
Library.Network.ServerPackets.CompanionAutoFeedUnlocked
Library.Network.ClientPackets.CompanionGridRefresh
Library.Network.ServerPackets.CompanionGridRefresh
Library.Network.ServerPackets.CompanionItemsGained
Library.Network.ClientPackets.CompanionItemsToInventory
Library.Network.ClientPackets.CompanionPickUpSkipUpdate
Library.Network.ClientPackets.CompanionRetrieve
Library.Network.ServerPackets.CompanionRetrieve
Library.Network.ServerPackets.CompanionShapeUpdate
Library.Network.ServerPackets.CompanionSkillUpdate
Library.Network.ClientPackets.CompanionStore
Library.Network.ServerPackets.CompanionStore
Library.Network.ClientPackets.CompanionUnlock
Library.Network.ServerPackets.CompanionUnlock
Library.Network.ServerPackets.CompanionUpdate
Library.Network.ServerPackets.CompanionWeightUpdate
Library.Network.ServerPackets.ConquestWarFlagFightEnd
Library.Network.ServerPackets.ConquestWarFlagFightStarted
Library.Network.ServerPackets.ContributeChanged
Library.Network.ClientPackets.ContributeRecharge
Library.Network.ServerPackets.CraftAcknowledged
Library.Network.ClientPackets.CraftCancel
Library.Network.ServerPackets.CraftExpChanged
Library.Network.ServerPackets.CraftResult
Library.Network.ClientPackets.CraftStart
Library.Network.ServerPackets.CraftStartFailed
Library.Network.ServerPackets.CustomNpc
Library.Network.ClientPackets.DKey
Library.Network.ServerPackets.DKey
Library.Network.ServerPackets.DataObjectHealthMana
Library.Network.ServerPackets.DataObjectItem
Library.Network.ServerPackets.DataObjectLocation
Library.Network.ServerPackets.DataObjectMaxHealthMana
Library.Network.ServerPackets.DataObjectMonster
Library.Network.ServerPackets.DataObjectPlayer
Library.Network.ServerPackets.DataObjectRemove
Library.Network.ServerPackets.DayChanged
Library.Network.ClientPackets.DeleteCharacter
Library.Network.ServerPackets.DeleteCharacter
Library.Network.ServerPackets.DiyObjectAttack
Library.Network.ServerPackets.DiyObjectEffect
Library.Network.ServerPackets.DiyObjectMagic
Library.Network.ClientPackets.EndGuildAlliance
Library.Network.ClientPackets.EnterAncientTomb
Library.Network.ServerPackets.Equipment
Library.Network.ClientPackets.Equipment
Library.Network.ClientPackets.FashionToggle
Library.Network.ServerPackets.FashionToggle
Library.Network.ClientPackets.FishingCast
Library.Network.ServerPackets.FishingEnded
Library.Network.ClientPackets.FishingReel
Library.Network.ServerPackets.FishingStarted
Library.Network.ClientPackets.FortuneCheck
Library.Network.ServerPackets.FortuneUpdate
Library.Network.ServerPackets.FreeCoinCountChanged
Library.Network.ClientPackets.FriendBotSummon
Library.Network.ServerPackets.FriendDelete
Library.Network.ClientPackets.FriendDeleteRequest
Library.Network.ServerPackets.FriendDeleteRequest
Library.Network.ServerPackets.FriendInvite
Library.Network.ServerPackets.FriendList
Library.Network.ServerPackets.FriendListRefresh
Library.Network.ServerPackets.FriendNew
Library.Network.ClientPackets.FriendRequest
Library.Network.ClientPackets.FriendResponse
Library.Network.ServerPackets.FriendSwitch
Library.Network.ClientPackets.FriendSwitch
Library.Network.ServerPackets.FriendToggle
Library.Network.ClientPackets.FriendToggle
Library.Network.ServerPackets.GainedExperience
Library.Network.ServerPackets.GameGoldChanged
Library.Network.ClientPackets.GameGoldRecharge
Library.Network.ServerPackets.GameLogout
Library.Network.ServerPackets.GateInformation
Library.Network.ClientPackets.GenderChange
Library.Network.ClientPackets.GetDailyQuest
Library.Network.ClientPackets.GetFixedPointinfo
Library.Network.ClientPackets.GetGuildApplications
Library.Network.ClientPackets.GetGuileWithDrawal
Library.Network.ClientPackets.GiveUpQuest
Library.Network.ServerPackets.GoldChanged
Library.Network.ClientPackets.GoldDrop
Library.Network.ClientPackets.GoldMarketCannel
Library.Network.ClientPackets.GoldMarketFlash
Library.Network.ClientPackets.GoldMarketGetOwnOrder
Library.Network.ServerPackets.GoldMarketList
Library.Network.ServerPackets.GoldMarketMyOrderList
Library.Network.ClientPackets.GoldMarketTrade
Library.Network.ServerPackets.GroupInvite
Library.Network.ClientPackets.GroupInvite
Library.Network.ServerPackets.GroupMember
Library.Network.ServerPackets.GroupRemove
Library.Network.ClientPackets.GroupRemove
Library.Network.ClientPackets.GroupResponse
Library.Network.ServerPackets.GroupSwitch
Library.Network.ClientPackets.GroupSwitch
Library.Network.ServerPackets.GuildActiveCountChange
Library.Network.ServerPackets.GuildAlliance
Library.Network.ClientPackets.GuildAlliance
Library.Network.ServerPackets.GuildAllianceEnded
Library.Network.ServerPackets.GuildAllianceStarted
Library.Network.ClientPackets.GuildAllowApplyChanged
Library.Network.ServerPackets.GuildAllyOffline
Library.Network.ServerPackets.GuildAllyOnline
Library.Network.ServerPackets.GuildApplications
Library.Network.ClientPackets.GuildApplyChoice
Library.Network.ServerPackets.GuildCastleInfo
Library.Network.ServerPackets.GuildChanged
Library.Network.ServerPackets.GuildConquestDate
Library.Network.ServerPackets.GuildConquestFinished
Library.Network.ServerPackets.GuildConquestStarted
Library.Network.ClientPackets.GuildCreate
Library.Network.ServerPackets.GuildCreate
Library.Network.ServerPackets.GuildDayReset
Library.Network.ClientPackets.GuildDonation
Library.Network.ClientPackets.GuildEditMember
Library.Network.ClientPackets.GuildEditNotice
Library.Network.ClientPackets.GuildEditVaultNotice
Library.Network.ClientPackets.GuildFlag
Library.Network.ServerPackets.GuildFundsChanged
Library.Network.ClientPackets.GuildGameGold
Library.Network.ServerPackets.GuildGetItem
Library.Network.ServerPackets.GuildIncreaseMember
Library.Network.ClientPackets.GuildIncreaseMember
Library.Network.ServerPackets.GuildIncreaseStorage
Library.Network.ClientPackets.GuildIncreaseStorage
Library.Network.ServerPackets.GuildInfo
Library.Network.ServerPackets.GuildInvite
Library.Network.ServerPackets.GuildInviteMember
Library.Network.ClientPackets.GuildInviteMember
Library.Network.ServerPackets.GuildKick
Library.Network.ClientPackets.GuildKickMember
Library.Network.ServerPackets.GuildMemberContribution
Library.Network.ServerPackets.GuildMemberOffline
Library.Network.ServerPackets.GuildMemberOnline
Library.Network.ServerPackets.GuildNewItem
Library.Network.ServerPackets.GuildNoticeChanged
Library.Network.ClientPackets.GuildRequestConquest
Library.Network.ClientPackets.GuildResponse
Library.Network.ServerPackets.GuildStats
Library.Network.ServerPackets.GuildTax
Library.Network.ClientPackets.GuildTax
Library.Network.ServerPackets.GuildToggle
Library.Network.ClientPackets.GuildToggle
Library.Network.ClientPackets.GuildUpdate
Library.Network.ServerPackets.GuildUpdate
Library.Network.ServerPackets.GuildVaultNoticeChanged
Library.Network.ServerPackets.GuildWar
Library.Network.ClientPackets.GuildWar
Library.Network.ServerPackets.GuildWarFinished
Library.Network.ServerPackets.GuildWarStarted
Library.Network.ServerPackets.GuildWithDrawal
Library.Network.ClientPackets.GuildWithdrawFund
Library.Network.ClientPackets.GuileWithdrawalApplyChoice
Library.Network.ClientPackets.HairChange
Library.Network.ClientPackets.Harvest
Library.Network.ServerPackets.HealthChanged
Library.Network.ServerPackets.HelmetToggle
Library.Network.ClientPackets.HelmetToggle
Library.Network.ClientPackets.Hermit
Library.Network.ClientPackets.HuiShengToggle
Library.Network.ServerPackets.HuiShengToggle
Library.Network.ServerPackets.HuntGoldChanged
Library.Network.ClientPackets.Inspect
Library.Network.ServerPackets.Inspect
Library.Network.ServerPackets.InspectMagery
Library.Network.ClientPackets.InspectMagery
Library.Network.ServerPackets.InspectPackSack
Library.Network.ClientPackets.InspectPackSack
Library.Network.ClientPackets.InventoryRefresh
Library.Network.ServerPackets.InventoryRefresh
Library.Network.ClientPackets.InventoryTidy
Library.Network.ServerPackets.ItemCellRefresh
Library.Network.ServerPackets.ItemChanged
Library.Network.ClientPackets.ItemDelete
Library.Network.ClientPackets.ItemDrop
Library.Network.ServerPackets.ItemDurability
Library.Network.ServerPackets.ItemExperience
Library.Network.ServerPackets.ItemLock
Library.Network.ClientPackets.ItemLock
Library.Network.ServerPackets.ItemMove
Library.Network.ClientPackets.ItemMove
Library.Network.ServerPackets.ItemRefineChange
Library.Network.ClientPackets.ItemSplit
Library.Network.ServerPackets.ItemSplit
Library.Network.ServerPackets.ItemStatsChanged
Library.Network.ServerPackets.ItemStatsRefreshed
Library.Network.ClientPackets.ItemUse
Library.Network.ServerPackets.ItemUseDelay
Library.Network.ServerPackets.ItemsChanged
Library.Network.ServerPackets.ItemsGained
Library.Network.ClientPackets.JoinStarterGuild
Library.Network.ServerPackets.LevelChanged
Library.Network.ClientPackets.Login
Library.Network.ServerPackets.Login
Library.Network.ClientPackets.Logout
Library.Network.ClientPackets.Magic
Library.Network.ServerPackets.MagicCooldown
Library.Network.ClientPackets.MagicKey
Library.Network.ServerPackets.MagicLeveled
Library.Network.ServerPackets.MagicToggle
Library.Network.ClientPackets.MagicToggle
Library.Network.ServerPackets.MailDelete
Library.Network.ClientPackets.MailDelete
Library.Network.ClientPackets.MailGetItem
Library.Network.ServerPackets.MailItemDelete
Library.Network.ServerPackets.MailList
Library.Network.ServerPackets.MailNew
Library.Network.ClientPackets.MailOpened
Library.Network.ClientPackets.MailSend
Library.Network.ServerPackets.MailSend
Library.Network.ServerPackets.ManaChanged
Library.Network.ServerPackets.MapChanged
Library.Network.ServerPackets.MapEffect
Library.Network.ServerPackets.MapMagicRestriction
Library.Network.ServerPackets.MapTime
Library.Network.ClientPackets.MarketPlaceBuy
Library.Network.ServerPackets.MarketPlaceBuy
Library.Network.ClientPackets.MarketPlaceCancelConsign
Library.Network.ClientPackets.MarketPlaceConsign
Library.Network.ServerPackets.MarketPlaceConsign
Library.Network.ServerPackets.MarketPlaceConsignChanged
Library.Network.ClientPackets.MarketPlaceHistory
Library.Network.ServerPackets.MarketPlaceHistory
Library.Network.ClientPackets.MarketPlaceJiaoseBuy
Library.Network.ServerPackets.MarketPlaceJiaoseBuy
Library.Network.ClientPackets.MarketPlaceSearch
Library.Network.ServerPackets.MarketPlaceSearch
Library.Network.ServerPackets.MarketPlaceSearchCount
Library.Network.ClientPackets.MarketPlaceSearchIndex
Library.Network.ServerPackets.MarketPlaceSearchIndex
Library.Network.ClientPackets.MarketPlaceStoreBuy
Library.Network.ServerPackets.MarketPlaceStoreBuy
Library.Network.ServerPackets.MarriageInfo
Library.Network.ServerPackets.MarriageInvite
Library.Network.ClientPackets.MarriageMakeRing
Library.Network.ServerPackets.MarriageMakeRing
Library.Network.ServerPackets.MarriageOnlineChanged
Library.Network.ServerPackets.MarriageRemoveRing
Library.Network.ClientPackets.MarriageResponse
Library.Network.ClientPackets.MarriageTeleport
Library.Network.ClientPackets.Mining
Library.Network.ClientPackets.Mount
Library.Network.ServerPackets.MountFailed
Library.Network.ClientPackets.Move
Library.Network.ServerPackets.NPCAccessoryLevelUp
Library.Network.ClientPackets.NPCAccessoryLevelUp
Library.Network.ClientPackets.NPCAccessoryReset
Library.Network.ClientPackets.NPCAccessoryUpgrade
Library.Network.ServerPackets.NPCAccessoryUpgrade
Library.Network.ClientPackets.NPCBookRefine
Library.Network.ClientPackets.NPCButton
Library.Network.ClientPackets.NPCBuy
Library.Network.ServerPackets.NPCBuyBack
Library.Network.ClientPackets.NPCBuyBack
Library.Network.ServerPackets.NPCBuyBackSeach
Library.Network.ClientPackets.NPCBuyBackSeach
Library.Network.ClientPackets.NPCCall
Library.Network.ServerPackets.NPCClose
Library.Network.ClientPackets.NPCClose
Library.Network.ClientPackets.NPCEnchantmentSynthesis
Library.Network.ClientPackets.NPCFragment
Library.Network.ClientPackets.NPCMasterRefine
Library.Network.ServerPackets.NPCMasterRefine
Library.Network.ClientPackets.NPCMasterRefineEvaluate
Library.Network.ClientPackets.NPCRefine
Library.Network.ServerPackets.NPCRefine
Library.Network.ServerPackets.NPCRefineRetrieve
Library.Network.ClientPackets.NPCRefineRetrieve
Library.Network.ClientPackets.NPCRefinementStone
Library.Network.ServerPackets.NPCRefinementStone
Library.Network.ServerPackets.NPCRepair
Library.Network.ClientPackets.NPCRepair
Library.Network.ServerPackets.NPCResponse
Library.Network.ClientPackets.NPCRootSell
Library.Network.ClientPackets.NPCSell
Library.Network.ServerPackets.NPCSpecialRepair
Library.Network.ClientPackets.NPCSpecialRepair
Library.Network.ClientPackets.NPCWeaponCraft
Library.Network.ServerPackets.NPCWeaponCraft
Library.Network.ServerPackets.NPCWeaponUpgrade
Library.Network.ClientPackets.NPCWeaponUpgrade
Library.Network.ClientPackets.NPCWeaponUpgradeRetrieve
Library.Network.ClientPackets.NameChange
Library.Network.ServerPackets.NewAccount
Library.Network.ClientPackets.NewAccount
Library.Network.ServerPackets.NewAuctionFlash
Library.Network.ServerPackets.NewAuctionFlashIndex
Library.Network.ServerPackets.NewCharacter
Library.Network.ClientPackets.NewCharacter
Library.Network.ServerPackets.NewMagic
Library.Network.ServerPackets.ObjectAttack
Library.Network.ServerPackets.ObjectBuffAdd
Library.Network.ServerPackets.ObjectBuffRemove
Library.Network.ServerPackets.ObjectDash
Library.Network.ServerPackets.ObjectDied
Library.Network.ServerPackets.ObjectEffect
Library.Network.ServerPackets.ObjectFishing
Library.Network.ServerPackets.ObjectHarvest
Library.Network.ServerPackets.ObjectHarvested
Library.Network.ServerPackets.ObjectHide
Library.Network.ServerPackets.ObjectItem
Library.Network.ServerPackets.ObjectLeveled
Library.Network.ServerPackets.ObjectMagic
Library.Network.ServerPackets.ObjectMining
Library.Network.ServerPackets.ObjectMonster
Library.Network.ServerPackets.ObjectMount
Library.Network.ServerPackets.ObjectMove
Library.Network.ServerPackets.ObjectNPC
Library.Network.ServerPackets.ObjectNameColour
Library.Network.ServerPackets.ObjectPetOwnerChanged
Library.Network.ServerPackets.ObjectPlayer
Library.Network.ServerPackets.ObjectPoison
Library.Network.ServerPackets.ObjectPushed
Library.Network.ServerPackets.ObjectRangeAttack
Library.Network.ServerPackets.ObjectRemove
Library.Network.ServerPackets.ObjectRevive
Library.Network.ServerPackets.ObjectShow
Library.Network.ServerPackets.ObjectSpell
Library.Network.ServerPackets.ObjectSpellChanged
Library.Network.ServerPackets.ObjectStats
Library.Network.ServerPackets.ObjectStruck
Library.Network.ServerPackets.ObjectTurn
Library.Network.ServerPackets.ObjectUseItem
Library.Network.ServerPackets.ObjectWeaponLeveled
Library.Network.ClientPackets.ObservableSwitch
Library.Network.ServerPackets.ObservableSwitch
Library.Network.ClientPackets.ObserverRequest
Library.Network.ServerPackets.PatchGridSize
Library.Network.ClientPackets.PickUp
Library.Network.ServerPackets.PlaySound
Library.Network.ServerPackets.PlayerChangeUpdate
Library.Network.ServerPackets.PlayerUpdate
Library.Network.ServerPackets.PrestigeChanged
Library.Network.ClientPackets.PrestigeRecharge
Library.Network.ServerPackets.PyTextBox
Library.Network.ClientPackets.PyTextBoxResponse
Library.Network.ClientPackets.QuestAccept
Library.Network.ServerPackets.QuestChanged
Library.Network.ClientPackets.QuestComplete
Library.Network.ServerPackets.QuestRemoved
Library.Network.ClientPackets.QuestTrack
Library.Network.ClientPackets.RankRequest
Library.Network.ServerPackets.Rankings
Library.Network.ClientPackets.ReCallToggle
Library.Network.ServerPackets.ReCallToggle
Library.Network.ServerPackets.ReFlashSellCharState
Library.Network.ServerPackets.RecentRedPackets
Library.Network.ServerPackets.RedPacketUpdate
Library.Network.ServerPackets.RefineList
Library.Network.ServerPackets.RemoveEffects
Library.Network.ClientPackets.RemoveGem
Library.Network.ClientPackets.RemoveTaishanBuff
Library.Network.ServerPackets.RequestActivationKey
Library.Network.ClientPackets.RequestActivationKey
Library.Network.ClientPackets.RequestPasswordReset
Library.Network.ServerPackets.RequestPasswordReset
Library.Network.ServerPackets.RequestProcessHash
Library.Network.ServerPackets.RequestStartGame
Library.Network.ClientPackets.RequestStartGame
Library.Network.ClientPackets.ResetPassword
Library.Network.ServerPackets.ResetPassword
Library.Network.ClientPackets.ResponseProcessHash
Library.Network.ServerPackets.ReviveTimers
Library.Network.ServerPackets.RewardPoolCoinChanged
Library.Network.ServerPackets.RewardPoolCoinRankChanged
Library.Network.ServerPackets.RewardPoolUpdate
Library.Network.ServerPackets.SafeZoneChanged
Library.Network.ClientPackets.SelectLanguage
Library.Network.ServerPackets.SelectLogout
Library.Network.ClientPackets.SellCharacter
Library.Network.ClientPackets.SellCharacterSearch
Library.Network.ServerPackets.SellCharacterSearch
Library.Network.ClientPackets.ShieldToggle
Library.Network.ServerPackets.ShieldToggle
Library.Network.ClientPackets.ShortcutDialogClicked
Library.Network.ServerPackets.ShortcutsLoaded
Library.Network.ServerPackets.ShowConfirmationBox
Library.Network.ServerPackets.ShowInputBox
Library.Network.ServerPackets.ShowItemSource
Library.Network.ClientPackets.StartGame
Library.Network.ServerPackets.StartGame
Library.Network.ServerPackets.StartObserver
Library.Network.ServerPackets.StatsUpdate
Library.Network.ClientPackets.StorageItemRefresh
Library.Network.ServerPackets.StorageItemRefresh
Library.Network.ServerPackets.StorageSize
Library.Network.ServerPackets.TaishanBuffChanged
Library.Network.ClientPackets.TakeOffAchievementTitle
Library.Network.ClientPackets.TeamHookLeaderLocation
Library.Network.ServerPackets.TeamHookLeaderLocation
Library.Network.ClientPackets.TeamHookTownSupply
Library.Network.ServerPackets.TeamHookTownSupply
Library.Network.ClientPackets.TeleportRing
Library.Network.ClientPackets.TossCoin
Library.Network.ClientPackets.TownRevive
Library.Network.ServerPackets.TradeAddGold
Library.Network.ClientPackets.TradeAddGold
Library.Network.ClientPackets.TradeAddItem
Library.Network.ServerPackets.TradeAddItem
Library.Network.ClientPackets.TradeClose
Library.Network.ServerPackets.TradeClose
Library.Network.ClientPackets.TradeConfirm
Library.Network.ServerPackets.TradeGoldAdded
Library.Network.ServerPackets.TradeItemAdded
Library.Network.ServerPackets.TradeOpen
Library.Network.ClientPackets.TradePartnerAddItem
Library.Network.ServerPackets.TradeRequest
Library.Network.ClientPackets.TradeRequest
Library.Network.ClientPackets.TradeRequestResponse
Library.Network.ClientPackets.TradeToggle
Library.Network.ServerPackets.TradeToggle
Library.Network.ServerPackets.TradeUnlock
Library.Network.ClientPackets.TreasureChange
Library.Network.ServerPackets.TreasureChest
Library.Network.ServerPackets.TreasureSel
Library.Network.ClientPackets.TreasureSelect
Library.Network.ClientPackets.Turn
Library.Network.ServerPackets.UpdateGuildGameTotal
Library.Network.ServerPackets.UpdateNPCLook
Library.Network.ServerPackets.UserLocation
Library.Network.ClientPackets.WarWeapAttackCoordinates
Library.Network.ClientPackets.WarWeapAttackStop
Library.Network.ServerPackets.WarWeapLocation
Library.Network.ClientPackets.WarWeapMove
Library.Network.ClientPackets.WearAchievementTitle
Library.Network.ServerPackets.WeightUpdate
Library.Network.ClientPackets.cs_FixedPoint
Library.Network.ClientPackets.cs_FixedPointMove
Library.Network.ServerPackets.sc_FixedPoint
Library.Network.ServerPackets.sc_FixedPointAdd
Library.Network.ServerPackets.sc_FixedPointList";

        internal static void Apply(List<Type> packets)
        {
            string[] names = WireOrderNames.Split('\n');
            if (packets.Count != names.Length)
                throw new InvalidOperationException("Original Android packet count mismatch.");
            var ids = new Dictionary<string, int>(StringComparer.Ordinal);
            for (int i = 0; i < names.Length; i++)
                ids.Add(names[i].TrimEnd('\r'), i);
            foreach (Type type in packets)
                if (!ids.ContainsKey(type.FullName))
                    throw new InvalidOperationException("Unknown original Android packet: " + type.FullName);
            packets.Sort((a, b) => ids[a.FullName].CompareTo(ids[b.FullName]));
        }
    }
}
#endif
